import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import FollowBar from "@/components/followbar/FollowBar";
import "@radix-ui/themes/styles.css";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await new Promise((resolve) => setTimeout(resolve, 3000));
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen bg-dark-bg text-dark-text ">
          <div className="container xl:px-30 h-full mx-auto max-w-6xl">
            <div className="grid grid-cols-4 h-full pt-4">
              <Sidebar />
              <div className="col-span-3 lg:col-span-2 border-x-[2px] border-neutral-800">
                {children}
              </div>
              <FollowBar/>
            </div>
          </div>
        </div>
      </body>
      
      
    </html>
  );
}
